---
 - name: Create a login user
   user:
      name: jenkins
      groups: # Empty by default, here we give it some groups
       - vagrant
       - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
